// <auto-generated />
using System;
using AppIntPrueba.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppIntPrueba.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221101223014_se agrega enlace de youtube")]
    partial class seagregaenlacedeyoutube
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AppIntPrueba.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistId"), 1L, 1);

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            ArtistName = "Metallica"
                        },
                        new
                        {
                            ArtistId = 2,
                            ArtistName = "Foo Fighters"
                        });
                });

            modelBuilder.Entity("AppIntPrueba.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"), 1L, 1);

                    b.Property<string>("CommentContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("SongId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("AppIntPrueba.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SongId"), 1L, 1);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int>("SongDislikes")
                        .HasColumnType("int");

                    b.Property<string>("SongImageRoute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SongLikes")
                        .HasColumnType("int");

                    b.Property<string>("SongName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SongRegistryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SongYoutubeRoute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SongId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            SongId = 1,
                            ArtistId = 1,
                            SongDislikes = 0,
                            SongImageRoute = "../../assets/nothing else matters.JPG",
                            SongLikes = 1,
                            SongName = "Nothing Else Matters",
                            SongRegistryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SongYoutubeRoute = "../../assets/tAGnKpE4NCI"
                        },
                        new
                        {
                            SongId = 2,
                            ArtistId = 1,
                            SongDislikes = 0,
                            SongImageRoute = "../../assets/master of puppets.JPG",
                            SongLikes = 1,
                            SongName = "Master of Pupets",
                            SongRegistryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SongYoutubeRoute = "../../assets/6xjJ2XIbGRk"
                        },
                        new
                        {
                            SongId = 3,
                            ArtistId = 1,
                            SongDislikes = 0,
                            SongImageRoute = "../../assets/the unforgiven.JPG",
                            SongLikes = 1,
                            SongName = "The Unforgiven",
                            SongRegistryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SongYoutubeRoute = "../../assets/DDGhKS6bSAE"
                        },
                        new
                        {
                            SongId = 4,
                            ArtistId = 1,
                            SongDislikes = 0,
                            SongImageRoute = "../../assets/one.JPG",
                            SongLikes = 1,
                            SongName = "One",
                            SongRegistryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SongYoutubeRoute = "../../assets/WM8bTdBs-cw"
                        },
                        new
                        {
                            SongId = 5,
                            ArtistId = 1,
                            SongDislikes = 0,
                            SongImageRoute = "../../assets/for whom the bells tolls.JPG",
                            SongLikes = 1,
                            SongName = "For Whom the Bell Tolls",
                            SongRegistryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SongYoutubeRoute = "../../assets/B_HSa1dEL9s"
                        },
                        new
                        {
                            SongId = 6,
                            ArtistId = 1,
                            SongDislikes = 0,
                            SongImageRoute = "../../assets/whiskey in the jar.JPG",
                            SongLikes = 1,
                            SongName = "Whiskey in the Jar",
                            SongRegistryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SongYoutubeRoute = "../../assets/boanuwUMNNQ"
                        },
                        new
                        {
                            SongId = 7,
                            ArtistId = 1,
                            SongDislikes = 0,
                            SongImageRoute = "../../assets/sadButTrue.JPG",
                            SongLikes = 1,
                            SongName = "Sad but True",
                            SongRegistryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SongYoutubeRoute = "../../assets/A8MO7fkZc5o"
                        },
                        new
                        {
                            SongId = 8,
                            ArtistId = 1,
                            SongDislikes = 0,
                            SongImageRoute = "../../assets/Everlong",
                            SongLikes = 1,
                            SongName = "Everlong",
                            SongRegistryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SongYoutubeRoute = "../../assets/eBG7P-K-r1Y"
                        },
                        new
                        {
                            SongId = 9,
                            ArtistId = 2,
                            SongDislikes = 0,
                            SongImageRoute = "../../assets/the pretender.JPG",
                            SongLikes = 1,
                            SongName = "The Pretender",
                            SongRegistryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SongYoutubeRoute = "../../assets/SBjQ9tuuTJQ"
                        },
                        new
                        {
                            SongId = 10,
                            ArtistId = 2,
                            SongDislikes = 0,
                            SongImageRoute = "../../assets/bestOfYou.JPG",
                            SongLikes = 1,
                            SongName = "Best of You",
                            SongRegistryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SongYoutubeRoute = "../../assets/h_L4Rixya64"
                        },
                        new
                        {
                            SongId = 11,
                            ArtistId = 2,
                            SongDislikes = 0,
                            SongImageRoute = "../../assets/my hero.PNG",
                            SongLikes = 1,
                            SongName = "My Hero",
                            SongRegistryDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SongYoutubeRoute = "../../assets/EqWRaAF6_WY"
                        });
                });

            modelBuilder.Entity("AppIntPrueba.Models.Comment", b =>
                {
                    b.HasOne("AppIntPrueba.Models.Song", "Song")
                        .WithMany("Comments")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("AppIntPrueba.Models.Song", b =>
                {
                    b.HasOne("AppIntPrueba.Models.Artist", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("AppIntPrueba.Models.Artist", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("AppIntPrueba.Models.Song", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
