// <auto-generated />
using System;
using AppIntPrueba.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppIntPrueba.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231202181945_inicio")]
    partial class inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AppIntPrueba.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"), 1L, 1);

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("MovieId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            CommentDate = new DateTime(2015, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Content = "Good movie",
                            MovieId = 1
                        },
                        new
                        {
                            CommentId = 21,
                            CommentDate = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Content = "Boring movie",
                            MovieId = 2
                        },
                        new
                        {
                            CommentId = 3,
                            CommentDate = new DateTime(2013, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Content = "I like it",
                            MovieId = 3
                        });
                });

            modelBuilder.Entity("AppIntPrueba.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ImageRoute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("TrailerLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Description = "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
                            Duration = "2h 30 min",
                            Genre = "Action, Sci-Fi",
                            ImageRoute = "../../assets/Tenet.png",
                            Rating = 7.7999999999999998,
                            ReleaseDate = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tenet",
                            TrailerLink = "https://www.youtube.com/watch?v=LdOM0x0XDMo"
                        },
                        new
                        {
                            MovieId = 2,
                            Description = "Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.",
                            Duration = "1h 57min",
                            Genre = "Action, Animation, Adventure",
                            ImageRoute = "../../assets/SpiderMan.png",
                            Rating = 8.4000000000000004,
                            ReleaseDate = new DateTime(2018, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spider-Man: Into the Spider-Verse",
                            TrailerLink = "https://www.youtube.com/watch?v=tg52up16eq0"
                        },
                        new
                        {
                            MovieId = 3,
                            Description = "A detective investigates the death of a patriarch of an eccentric, combative family",
                            Duration = "2h 10min",
                            Genre = "Comedy, Crime, Drama",
                            ImageRoute = "../../assets/KnivesOut.png",
                            Rating = 7.9000000000000004,
                            ReleaseDate = new DateTime(2019, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Knives Out",
                            TrailerLink = "https://www.youtube.com/watch?v=qGqiHJTsRkQ"
                        },
                        new
                        {
                            MovieId = 4,
                            Description = "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
                            Duration = "2h 1min",
                            Genre = "Action, Adventure, Comedy",
                            ImageRoute = "../../assets/GuardiansOfTheGalaxy.png",
                            Rating = 8.0,
                            ReleaseDate = new DateTime(2014, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Guardians of the Galaxy",
                            TrailerLink = "https://www.youtube.com/watch?v=d96cjJhvlMA"
                        },
                        new
                        {
                            MovieId = 5,
                            Description = "When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's mightiest heroes to stop the villainous Ultron from enacting his terrible plan.",
                            Duration = "2h 21min",
                            Genre = "Action, Adventure, Sci-Fi",
                            ImageRoute = "../../assets/Avengers.png",
                            Rating = 7.2999999999999998,
                            ReleaseDate = new DateTime(2015, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avengers: Age of Ultron",
                            TrailerLink = "https://www.youtube.com/watch?v=tmeOjFno6Do"
                        });
                });

            modelBuilder.Entity("AppIntPrueba.Models.Comment", b =>
                {
                    b.HasOne("AppIntPrueba.Models.Movie", "Movie")
                        .WithMany("Comments")
                        .HasForeignKey("MovieId");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("AppIntPrueba.Models.Movie", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
